### PR TITLE
Server api

### PR DESCRIPTION
**Pull request by Corliosity**
Merging code for the GET and POST methods via JSON on the podcast episodes route.

Updating GET for RSS XML feed to iTunes.

@tdalziel

### CODE REVIEW

**Comment by Corliosity** [comment]
Also, @jordwms if you want to take a look at some NODE with API take a look.

**Comment by jordwms** [comment]
Sure! :)

**Comment by Corliosity** [comment]
Thanks @jordwms Everything should now be in place!  Maybe I should show this to JAVA
Tell them I can do services now. lol

**Comment by Corliosity** [comment]
Margining, Note to self: set clean up tasks.

**Pull request merged**
